Add node dependency

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,10 +1,13 @@
 #!/bin/sh
+set -e # halt script on error
+
 echo "==> Building the site…"
-- set -e 
 bundle exec jekyll build
 ls -l
+
+
 # #!/usr/bin/env bash
-# set -e # halt script on error
+
 
 # bundle exec jekyll build
 # bundle exec htmlproofer ./_site
